# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  server:
    build:
      context: .
    depends_on:
      # - postgres
      postgres:
        condition: service_healthy
    
    ports:
      - "8080:8080"
    restart: on-failure
    command: [ "/app/main" ]


  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 2s
      retries: 2
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  